version: 0.0
os: linux

env:
  variables:
    APP_NAME: MyJavaEc2App
    VERSION: 1.0.0

files:
  - source: /  # Reference the ZIP file as the source artifact
    destination: /home/ec2-user/app  # Destination for the ZIP file

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  BeforeInstall:
    - location: deploy_scripts/check_java_version.sh  # Use the external script
      runas: ec2-user

  ApplicationStop:
    - location: deploy_scripts/stop.sh
      runas: ec2-user

  ApplicationStart:
    - location: deploy_scripts/start.sh
      runas: ec2-user

  ValidateService:
    - location: deploy_scripts/validate.sh
      runas: ec2-user
