version: 0.0
os: linux

env:
  variables:
    APP_NAME: MyJavaEc2App
    VERSION: 1.0.0

files:
  - source: $APP_NAME-$VERSION.zip  # Reference the ZIP file as the source artifact
    destination: /home/ec2-user/app  # Destination for the ZIP file

permissions:
  - object: /home/ec2-user/app/deploy_scripts/*.sh  # Ensure scripts have proper permissions
    pattern: "**"
    owner: ec2-user
    group: ec2-user

  - object: /home/ec2-user/app/target/*.jar  # Ensure the JAR file has proper permissions
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  BeforeInstall:
    - location: /home/ec2-user/app/deploy_scripts/extract_and_set_permissions.sh  # Use the external script
      runas: ec2-user

  ApplicationStop:
    - location: /home/ec2-user/app/deploy_scripts/stop.sh
      runas: ec2-user

  ApplicationStart:
    - location: /home/ec2-user/app/deploy_scripts/start.sh
      runas: ec2-user

  ValidateService:
    - location: /home/ec2-user/app/deploy_scripts/validate.sh
      runas: ec2-user
