name: Java CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  id-token: write
  packages: write
  actions: write

jobs:
  pipeline:
    uses: uj-cpu-dev/deploy-to-aws-ecr/.github/workflows/ci-cd.yml@main
    with:
      language: java